### PR TITLE
[Discussion] link boost

### PR DESCRIPTION
**Pull request by looooo**
this is not yet working, but I need some input for further progress.
The linking problems with SMESHUtils are gone, but now libSMESH.so makes problems:

```
ImportError: /home/lo/conda/envs/pyocct/lib/python3.6/site-packages/OCCT/../../../libSMESH.so: undefined symbol: _ZTIN5boost6detail16thread_data_baseE
```

I have no idea what I am doing wrong here. Maybe @shrdluk can help.

### CODE REVIEW

**Comment by looooo** [comment]
is it possible to compile without boost::thread?

**Comment by shrdluk** [comment]
> ImportError: /home/lo/conda/envs/pyocct/lib/python3.6/site-packages/OCCT/../../../libSMESH.so: undefined symbol: _ZTIN5boost6detail16thread_data_baseE

Unmangling the missing symbol:
```
$ c++filt _ZTIN5boost6detail16thread_data_baseE
typeinfo for boost::detail::thread_data_base
```
Does libSMESH.so need to be linked with whatever contains `boost::detail::thread_data_base` when it is built? Or possibly Python needs to be able to find it at run time.

**Comment by looooo** [comment]
Sry, my problem was related to conda. Somehow the smesh-library wasn't updated. I guess there was a change introduced with newer conda-version. After deleting all smesh-pkgs and reinstalling smesh again, the imports did work.
So the reported problem was related to an older build. After using a build with the changes for boost (this PR) everything seems to work fine.

**Comment by shrdluk** [comment]
> After deleting all smesh-pkgs and reinstalling smesh again, the imports did work.

Ah, the old "have you tried turning it off and on again?" solution :smile:

**Comment by looooo** [comment]
yes thats really a problem of builds with the same name. conda assumes the package is allready pulled and installs an old version.

**Comment by looooo** [comment]
@trelau  thanks for merging

**Comment by shrdluk** [comment]
Yes, I've fallen foul of that one. Conda is very keen on reusing the version it's already got. I now delete the old package in miniconda3/pkgs _and_ its zip file to ensure it loads the new package.

**Comment by looooo** [comment]
exactly this was my conclusion after the mess today ; )

**Pull request merged**
